# ============================================
# Prometheus ConfigMap (簡化版 - 移除 cAdvisor)
# ============================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']

      # Nginx Ingress Controller metrics
      - job_name: 'nginx-ingress'
        static_configs:
          - targets: ['ingress-nginx-controller-metrics.ingress-nginx.svc.cluster.local:10254']

---
# ============================================
# Grafana Datasource ConfigMap
# ============================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: false
        uid: prometheus

---
# ============================================
# Grafana Dashboard Provider ConfigMap
# ============================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider
data:
  dashboards.yml: |
    apiVersion: 1
    providers:
      - name: 'Stress Test Dashboards'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards

---
# ============================================
# Grafana Dashboard JSON ConfigMap
# ============================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
data:
  stress-test.json: |
    {
      "annotations": {"list": []},
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": null,
      "links": [],
      "panels": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "color": {"mode": "palette-classic"},
              "custom": {
                "axisBorderShow": false,
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 10,
                "gradientMode": "none",
                "hideFrom": {"tooltip": false, "viz": false, "legend": false},
                "insertNulls": false,
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {"type": "linear"},
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {"group": "A", "mode": "none"},
                "thresholdsStyle": {"mode": "off"}
              },
              "mappings": [],
              "max": 100,
              "min": 0,
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {"color": "green", "value": null},
                  {"color": "red", "value": 80}
                ]
              },
              "unit": "percent"
            },
            "overrides": []
          },
          "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0},
          "id": 1,
          "options": {
            "legend": {"calcs": [], "displayMode": "list", "placement": "bottom", "showLegend": true},
            "tooltip": {"mode": "single", "sort": "none"}
          },
          "targets": [
            {
              "datasource": {"type": "prometheus", "uid": "prometheus"},
              "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
              "refId": "A",
              "legendFormat": "CPU 使用率"
            }
          ],
          "title": "CPU 使用率 (%)",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "color": {"mode": "palette-classic"},
              "custom": {
                "axisBorderShow": false,
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 10,
                "gradientMode": "none",
                "hideFrom": {"tooltip": false, "viz": false, "legend": false},
                "insertNulls": false,
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {"type": "linear"},
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {"group": "A", "mode": "none"},
                "thresholdsStyle": {"mode": "off"}
              },
              "mappings": [],
              "max": 100,
              "min": 0,
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {"color": "green", "value": null},
                  {"color": "red", "value": 80}
                ]
              },
              "unit": "percent"
            },
            "overrides": []
          },
          "gridPos": {"h": 8, "w": 12, "x": 12, "y": 0},
          "id": 2,
          "options": {
            "legend": {"calcs": [], "displayMode": "list", "placement": "bottom", "showLegend": true},
            "tooltip": {"mode": "single", "sort": "none"}
          },
          "targets": [
            {
              "datasource": {"type": "prometheus", "uid": "prometheus"},
              "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
              "refId": "A",
              "legendFormat": "記憶體使用率"
            }
          ],
          "title": "記憶體使用率 (%)",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "color": {"mode": "palette-classic"},
              "custom": {
                "axisBorderShow": false,
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 10,
                "gradientMode": "none",
                "hideFrom": {"tooltip": false, "viz": false, "legend": false},
                "insertNulls": false,
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {"type": "linear"},
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {"group": "A", "mode": "none"},
                "thresholdsStyle": {"mode": "off"}
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [{"color": "green", "value": null}]
              },
              "unit": "MBs"
            },
            "overrides": []
          },
          "gridPos": {"h": 8, "w": 12, "x": 0, "y": 8},
          "id": 3,
          "options": {
            "legend": {"calcs": [], "displayMode": "list", "placement": "bottom", "showLegend": true},
            "tooltip": {"mode": "single", "sort": "none"}
          },
          "targets": [
            {
              "datasource": {"type": "prometheus", "uid": "prometheus"},
              "expr": "irate(node_network_receive_bytes_total{device!=\"lo\"}[1m]) / 1024 / 1024",
              "refId": "A",
              "legendFormat": "入站 - {{device}}"
            },
            {
              "datasource": {"type": "prometheus", "uid": "prometheus"},
              "expr": "irate(node_network_transmit_bytes_total{device!=\"lo\"}[1m]) / 1024 / 1024",
              "refId": "B",
              "legendFormat": "出站 - {{device}}"
            }
          ],
          "title": "網路 I/O (MB/s)",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "color": {"mode": "palette-classic"},
              "custom": {
                "axisBorderShow": false,
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 10,
                "gradientMode": "none",
                "hideFrom": {"tooltip": false, "viz": false, "legend": false},
                "insertNulls": false,
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {"type": "linear"},
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {"group": "A", "mode": "none"},
                "thresholdsStyle": {"mode": "off"}
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [{"color": "green", "value": null}]
              },
              "unit": "short"
            },
            "overrides": []
          },
          "gridPos": {"h": 8, "w": 12, "x": 12, "y": 8},
          "id": 4,
          "options": {
            "legend": {"calcs": [], "displayMode": "list", "placement": "bottom", "showLegend": true},
            "tooltip": {"mode": "single", "sort": "none"}
          },
          "targets": [
            {
              "datasource": {"type": "prometheus", "uid": "prometheus"},
              "expr": "nginx_ingress_controller_nginx_process_connections{state=\"active\"}",
              "refId": "A",
              "legendFormat": "活動連線"
            },
            {
              "datasource": {"type": "prometheus", "uid": "prometheus"},
              "expr": "nginx_ingress_controller_nginx_process_connections{state=\"reading\"}",
              "refId": "B",
              "legendFormat": "讀取中"
            },
            {
              "datasource": {"type": "prometheus", "uid": "prometheus"},
              "expr": "nginx_ingress_controller_nginx_process_connections{state=\"writing\"}",
              "refId": "C",
              "legendFormat": "寫入中"
            }
          ],
          "title": "Nginx Ingress 連線數",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "color": {"mode": "palette-classic"},
              "custom": {
                "axisBorderShow": false,
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 10,
                "gradientMode": "none",
                "hideFrom": {"tooltip": false, "viz": false, "legend": false},
                "insertNulls": false,
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {"type": "linear"},
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {"group": "A", "mode": "none"},
                "thresholdsStyle": {"mode": "off"}
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [{"color": "green", "value": null}]
              },
              "unit": "reqps"
            },
            "overrides": []
          },
          "gridPos": {"h": 8, "w": 12, "x": 0, "y": 16},
          "id": 6,
          "options": {
            "legend": {"calcs": [], "displayMode": "list", "placement": "bottom", "showLegend": true},
            "tooltip": {"mode": "single", "sort": "none"}
          },
          "targets": [
            {
              "datasource": {"type": "prometheus", "uid": "prometheus"},
              "expr": "sum(rate(nginx_ingress_controller_requests[1m]))",
              "refId": "A",
              "legendFormat": "總請求速率"
            }
          ],
          "title": "Nginx Ingress 請求速率 (req/s)",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "color": {"mode": "thresholds"},
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {"color": "green", "value": null},
                  {"color": "yellow", "value": 70},
                  {"color": "red", "value": 90}
                ]
              },
              "unit": "short"
            },
            "overrides": []
          },
          "gridPos": {"h": 8, "w": 12, "x": 12, "y": 16},
          "id": 5,
          "options": {
            "colorMode": "value",
            "graphMode": "area",
            "justifyMode": "auto",
            "orientation": "auto",
            "reduceOptions": {"values": false, "calcs": ["lastNotNull"], "fields": ""},
            "showPercentChange": false,
            "textMode": "auto",
            "wideLayout": true
          },
          "pluginVersion": "11.0.0",
          "targets": [
            {
              "datasource": {"type": "prometheus", "uid": "prometheus"},
              "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
              "refId": "A",
              "legendFormat": "CPU %"
            },
            {
              "datasource": {"type": "prometheus", "uid": "prometheus"},
              "expr": "(1 - (avg(node_memory_MemAvailable_bytes) / avg(node_memory_MemTotal_bytes))) * 100",
              "refId": "B",
              "legendFormat": "記憶體 %"
            },
            {
              "datasource": {"type": "prometheus", "uid": "prometheus"},
              "expr": "sum(nginx_ingress_controller_nginx_process_connections{state=\"active\"})",
              "refId": "C",
              "legendFormat": "連線數"
            }
          ],
          "title": "關鍵指標總覽",
          "type": "stat"
        }
      ],
      "refresh": "5s",
      "schemaVersion": 39,
      "tags": ["stress-test"],
      "templating": {"list": []},
      "time": {"from": "now-15m", "to": "now"},
      "timepicker": {},
      "timezone": "browser",
      "title": "壓力測試監控儀表板",
      "uid": "stress-test-dashboard",
      "version": 3,
      "weekStart": ""
    }

---
# ============================================
# Prometheus Deployment
# ============================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        args:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--storage.tsdb.path=/prometheus'
          - '--web.console.libraries=/usr/share/prometheus/console_libraries'
          - '--web.console.templates=/usr/share/prometheus/consoles'
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: config
        configMap:
          name: prometheus-config

---
# ============================================
# Prometheus Service
# ============================================
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090

---
# ============================================
# Grafana Deployment
# ============================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"
        volumeMounts:
        - name: datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: dashboard-provider
          mountPath: /etc/grafana/provisioning/dashboards
        - name: dashboards
          mountPath: /var/lib/grafana/dashboards
      volumes:
      - name: datasources
        configMap:
          name: grafana-datasources
      - name: dashboard-provider
        configMap:
          name: grafana-dashboard-provider
      - name: dashboards
        configMap:
          name: grafana-dashboards

---
# ============================================
# Grafana Service
# ============================================
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300

---
# ============================================
# Node Exporter DaemonSet
# ============================================
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: node-exporter
        image: prom/node-exporter:latest
        args:
          - '--path.procfs=/host/proc'
          - '--path.sysfs=/host/sys'
          - '--path.rootfs=/host/root'
          - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
        ports:
        - containerPort: 9100
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: root
          mountPath: /host/root
          readOnly: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: root
        hostPath:
          path: /

---
# ============================================
# Node Exporter Service
# ============================================
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
spec:
  selector:
    app: node-exporter
  ports:
  - port: 9100
    targetPort: 9100